AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for DynamoDB tables used by the Gardening Agent

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name

Resources:
  # DynamoDB tables will be defined here
  
Outputs:
  # Outputs will be defined here