AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function and layer for the Gardening Agent'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name (dev or prod)
  
  ProjectName:
    Type: String
    Default: gardening-agent
    Description: Name of the project, used as a prefix for resource names
  
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the Lambda execution role

Resources:
  # Lambda Layer
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub ${ProjectName}-${Environment}-dependencies
      Description: Dependencies for the Gardening Agent Lambda function
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
      Content:
        S3Bucket: !Ref 'AWS::NoValue'  # Replace with your S3 bucket name
        S3Key: !Ref 'AWS::NoValue'      # Replace with your S3 key for the layer zip
      # Note: You'll need to package the dependencies from lambda-layer/requirements.txt
      # and upload to S3 before deploying this template

  # Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Environment}
      Description: Gardening Agent Lambda function
      Runtime: python3.9
      Handler: agent.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref LambdaLayer
      Code:
        S3Bucket: !Ref 'AWS::NoValue'  # Replace with your S3 bucket name
        S3Key: !Ref 'AWS::NoValue'      # Replace with your S3 key for the function zip
      Environment:
        Variables:
          USER_DATA_TABLE_NAME: plant_database_users
          PLANT_DEFINITIONS_TABLE_NAME: garden_plants
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
  
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction